//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamificationPortal {
    
    
    public partial class Profile {
        
        /// <summary>
        /// PageControlProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTabControl.ASPxPageControl PageControlProfile;
        
        /// <summary>
        /// CurrentMission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.CurrentMission CurrentMission;
        
        /// <summary>
        /// UserProfile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.UserProfile UserProfile1;
        
        /// <summary>
        /// UsersHistory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.UsersMissions UsersHistory1;
        
        /// <summary>
        /// UserAchevements1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.UserAchevements UserAchevements1;
        
        /// <summary>
        /// ManageMissions1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.ManageMissions ManageMissions1;
        
        /// <summary>
        /// FIrstLoginSplashScreen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GamificationPortal.Controls.FIrstLoginSplashScreen FIrstLoginSplashScreen;
    }
}
