//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamificationPortal {
    
    
    public partial class SiteMap {
        
        /// <summary>
        /// ASPxSiteMapDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSiteMapControl.ASPxSiteMapDataSource ASPxSiteMapDataSource1;
        
        /// <summary>
        /// ASPxSiteMapControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSiteMapControl.ASPxSiteMapControl ASPxSiteMapControl1;
    }
}
